# Generated by Django 3.2.5 on 2021-08-05 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_auto_20210805_1545'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Certificate_test',
        ),
    ]
