# Generated by Django 3.2.5 on 2021-08-05 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlistentry',
            options={'verbose_name_plural': 'Waitlist entries'},
        ),
        migrations.AlterField(
            model_name='waitlistentry',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
    ]
