# Generated by Django 3.2.5 on 2021-08-05 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='lecture_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
