# Generated by Django 3.2.5 on 2021-08-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_lecture_lecture_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='notes',
        ),
        migrations.AddField(
            model_name='lecture',
            name='duration',
            field=models.IntegerField(default=2, help_text='Enter number of hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecture',
            name='is_requird',
            field=models.BooleanField(default=True),
        ),
    ]
